import { motion } from "framer-motion";
import Head from "next/head";
import Link from "next/link";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Experience from "../components/Experience";
import Header from "../components/Header";
import Identitiy from "../components/Identitiy";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory
     overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20
     scrollbar-thumb-[#f7ab0a]/80">
      <Head>
        <title>Joachim`s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/jaykimsly/image/upload/v1668129062/Portfolio/IMG_20200701_165038_kdrvom.jpg"
        />
      </Head>

      {/* Header */}
      <Header></Header>
      {/* Identitiy   */}
      <section id="Identitiy" className="snap-start">
        <Identitiy></Identitiy>
      </section>
      {/* About */}
      <section id="about" className="snap-center">
        <About></About>
      </section>
      {/* Experience */}
      <section id="experience" className="snap-center">
        <Experience></Experience>
      </section>
      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skills></Skills>
      </section>
      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects></Projects>
      </section>
      {/* Contact ME */}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>

      <Link href='#Identitiy'>
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div>
            <motion.img className="h-10 w-10 rounded-full filter grayscale hover:grayscale-0"
              src="https://res.cloudinary.com/jaykimsly/image/upload/v1668129158/Portfolio/2017-06-19-15-34-49-383_e2hhjo.jpg" alt="" />
          </div>
        </footer>
      </Link>

    </div>
  );
}
